apiVersion: apps/v1
kind: Deployment
metadata:
  name: compose-post-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: compose-post-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/socialnetwork-default: "true"
        io.kompose.service: compose-post-service
    spec:
      containers:
        - command:
            - ComposePostService
          image: deathstarbench/social-network-microservices:latest
          name: compose-post-service
          resources: {}
          volumeMounts:
            - mountPath: /social-network-microservices/config
              name: config
      hostname: compose-post-service
      restartPolicy: Always
      volumes:
        - name: config 
          hostPath:
            path: /home/vm_test/DeathStarBench/socialNetwork/config
            type: Directory
status: {}
