apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: home-timeline-redis
  name: home-timeline-redis
  namespace: default
spec:
  ports:
    - name: "6381"
      port: 6381
      targetPort: 6379
  selector:
    io.kompose.service: home-timeline-redis
status:
  loadBalancer: {}
