apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger-agent
  name: jaeger-agent
  namespace: default
spec:
  ports:
    - name: "16686"
      port: 16686
      targetPort: 16686
  selector:
    io.kompose.service: jaeger-agent
status:
  loadBalancer: {}
