apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger-agent
  name: jaeger-agent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jaeger-agent
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/socialnetwork-default: "true"
        io.kompose.service: jaeger-agent
    spec:
      containers:
        - env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
          image: jaegertracing/all-in-one:latest
          name: jaeger-agent
          ports:
            - containerPort: 16686
              hostPort: 16686
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
