apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: media-mongodb
  name: media-mongodb
  namespace: default
spec:
  ports:
    - name: "27024"
      port: 27024
      targetPort: 27017
  selector:
    io.kompose.service: media-mongodb
status:
  loadBalancer: {}
