---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: media-frontend
  name: media-frontend
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8080
    name: tcp
    targetPort: 8080
    nodePort: 31001
  selector:
    io.kompose.service: media-frontend
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: media-frontend
  name: media-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: media-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/socialnetwork-default: "true"
        io.kompose.service: media-frontend
    spec:
      containers:
        - image: yg397/media-frontend:xenial
          name: media-frontend
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/openresty/nginx/lua-scripts
              name: media-frontend-hostpath0
            - mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              name: media-frontend-hostpath1
      hostname: media-frontend
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/vm_test/DeathStarBench/socialNetwork/media-frontend/lua-scripts
          name: media-frontend-hostpath0
        - hostPath:
            path: /home/vm_test/DeathStarBench/socialNetwork/media-frontend/conf/nginx.conf
          name: media-frontend-hostpath1
status: {}
