apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: media-memcached
  name: media-memcached
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: media-memcached
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/socialnetwork-default: "true"
        io.kompose.service: media-memcached
    spec:
      containers:
        - image: memcached
          name: media-memcached
          ports:
            - containerPort: 11211
              hostPort: 11215
              protocol: TCP
          resources: {}
      hostname: media-memcached
      restartPolicy: Always
status: {}
