apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: media-frontend
  name: media-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: media-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/socialnetwork-default: "true"
        io.kompose.service: media-frontend
    spec:
      containers:
        - image: yg397/media-frontend:xenial
          name: media-frontend
          ports:
            - containerPort: 8080
              hostPort: 8081
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/openresty/nginx/lua-scripts
              name: lua-scripts
            - mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              name: nginx-conf 
      hostname: media-frontend
      restartPolicy: Always
      volumes:
        - name: lua-scripts
          hostPath:
            path: /home/vm_test/DeathStarBench/socialNetwork/nginx-web-server/lua-scripts
            type: Directory
        - name: nginx-conf
          hostPath:
            path: /home/vm_test/DeathStarBench/socialNetwork/media-frontend/conf/nginx.conf
            type: File
status: {}
