apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: "kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert"
    kompose.version: "1.30.0 (9d8dcb518)"
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-thrift
  name: nginx-thrift
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx-thrift
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: "kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert"
        kompose.version: "1.30.0 (9d8dcb518)"
      creationTimestamp: null
      labels:
        io.kompose.network/socialnetwork-default: "true"
        io.kompose.service: nginx-thrift
    spec:
      containers:
        - image: yg397/openresty-thrift:xenial
          name: nginx-thrift
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/openresty/nginx/lua-scripts
              name: lua-scripts
            - mountPath: /usr/local/openresty/nginx/pages
              name: pages
            - mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              name: nginx-conf
            - mountPath: /usr/local/openresty/nginx/jaeger-config.json
              name: jaeger-config-json
            - mountPath: /gen-lua
              name: gen-lua
      hostname: nginx-thrift
      restartPolicy: Always
      volumes:
        - name: lua-scripts
          hostPath:
            path: /home/vm_test/DeathStarBench/socialNetwork/nginx-web-server/lua-scripts
            type: Directory
        - name: pages
          hostPath:
            path: /home/vm_test/DeathStarBench/socialNetwork/nginx-web-server/pages
            type: Directory
        - name: nginx-conf
          hostPath:
            path: /home/vm_test/DeathStarBench/socialNetwork/nginx-web-server/conf/nginx.conf
            type: File
        - name: jaeger-config-json
          hostPath:
            path: /home/vm_test/DeathStarBench/socialNetwork/nginx-web-server/jaeger-config.json
            type: File
        - name: gen-lua
          hostPath:
            path: /home/vm_test/DeathStarBench/socialNetwork/gen-lua
            type: Directory
status: {}

