apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-thrift
  name: nginx-thrift
  namespace: default
spec:
  type: NodePort
  ports:
    - name: "http"  # Name for this port configuration
      port: 8080    # Port exposed within the cluster
      targetPort: 8080  # Port your service is listening on
      nodePort: 30000   # Port accessible externally on nodes
  selector:
    io.kompose.service: nginx-thrift

