apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: post-storage-service
  name: post-storage-service
  namespace: default
spec:
  ports:
    - name: "10002"
      port: 10002
      targetPort: 9090
  selector:
    io.kompose.service: post-storage-service
status:
  loadBalancer: {}
