apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: post-storage-memcached
  name: post-storage-memcached
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: post-storage-memcached
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/socialnetwork-default: "true"
        io.kompose.service: post-storage-memcached
    spec:
      containers:
        - image: memcached
          name: post-storage-memcached
          resources: {}
      hostname: post-storage-memcached
      restartPolicy: Always
status: {}
