apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: social-graph-redis
  name: social-graph-redis
  namespace: default
spec:
  ports:
    - name: "6380"
      port: 6380
      targetPort: 6379
  selector:
    io.kompose.service: social-graph-redis
status:
  loadBalancer: {}
