---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: social-graph-mongodb
  name: social-graph-mongodb
  namespace: social-network
spec:
  ports:
    - name: mongo
      port: 27017
  selector:
    io.kompose.service: social-graph-mongodb
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: social-graph-mongodb
  name: social-graph-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: social-graph-mongodb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/socialnetwork-default: "true"
        io.kompose.service: social-graph-mongodb
    spec:
      containers:
        - image: mongo:4.4.6
          name: social-graph-mongodb
          resources:
            limits:
              cpu: "1"
      hostname: social-graph-mongodb
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: vmworker5
status: {}
