---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: social-graph-redis
  name: social-graph-redis
  namespace: default
spec:
  ports:
    - name: "6380"
      port: 6380
      targetPort: 6379
  selector:
    io.kompose.service: social-graph-redis
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: social-graph-redis
  name: social-graph-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: social-graph-redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/socialnetwork-default: "true"
        io.kompose.service: social-graph-redis
    spec:
      containers:
        - image: redis
          name: social-graph-redis
          ports:
            - containerPort: 6379
              hostPort: 6380
              protocol: TCP
          resources: {}
      hostname: social-graph-redis
      restartPolicy: Always
status: {}
