---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: social-graph-service
  name: social-graph-service
  namespace: social-network
spec:
  ports:
    - name: tcp
      port: 9090
  selector:
    io.kompose.service: social-graph-service
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: social-graph-service
  name: social-graph-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: social-graph-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/socialnetwork-default: "true"
        io.kompose.service: social-graph-service
    spec:
      containers:
        - command:
            - SocialGraphService
          image: deathstarbench/social-network-microservices:latest
          name: social-graph-service
          resources: {}
          volumeMounts:
            - mountPath: /social-network-microservices/config
              name: social-graph-service-hostpath0
      hostname: social-graph-service
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/vm_test/DeathStarBench/socialNetwork/config
          name: social-graph-service-hostpath0
status: {}
