---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: text-service
  name: text-service
  namespace: default
spec:
  ports:
    - name: "10007"
      port: 10007
      targetPort: 9090
  selector:
    io.kompose.service: text-service
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: text-service
  name: text-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: text-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/socialnetwork-default: "true"
        io.kompose.service: text-service
    spec:
      containers:
        - command:
            - TextService
          image: deathstarbench/social-network-microservices:latest
          name: text-service
          ports:
            - containerPort: 9090
              hostPort: 10007
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /social-network-microservices/config
              name: text-service-hostpath0
      hostname: text-service
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/vm_test/DeathStarBench/socialNetwork/config
          name: text-service-hostpath0
status: {}
