apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: unique-id-service
  name: unique-id-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: unique-id-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert --volumes hostPath
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/socialnetwork-default: "true"
        io.kompose.service: unique-id-service
    spec:
      containers:
        - command:
            - UniqueIdService
          image: deathstarbench/social-network-microservices:latest
          name: unique-id-service
          ports:
            - containerPort: 9090
              hostPort: 10008
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /social-network-microservices/config
              name: unique-id-service-hostpath0
      hostname: unique-id-service
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/vm_test/DeathStarBench/socialNetwork/config
          name: unique-id-service-hostpath0
status: {}
