---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: url-shorten-memcached
  name: url-shorten-memcached
  namespace: social-network
spec:
  ports:
    - name: tcp
      port: 11211
  selector:
    io.kompose.service: url-shorten-memcached
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: url-shorten-memcached
  name: url-shorten-memcached
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: url-shorten-memcached
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/socialnetwork-default: "true"
        io.kompose.service: url-shorten-memcached
    spec:
      containers:
        - image: memcached
          name: url-shorten-memcached
          resources:
            limits:
              cpu: "1"
      hostname: url-shorten-memcached
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: vmworker6
status: {}
