apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: url-shorten-mongodb
  name: url-shorten-mongodb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: url-shorten-mongodb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert --volumes hostPath
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/socialnetwork-default: "true"
        io.kompose.service: url-shorten-mongodb
    spec:
      containers:
        - image: mongo:4.4.6
          name: url-shorten-mongodb
          ports:
            - containerPort: 27017
              hostPort: 27021
              protocol: TCP
          resources: {}
      hostname: url-shorten-mongodb
      restartPolicy: Always
status: {}
