apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: url-shorten-memcached
  name: url-shorten-memcached
  namespace: default
spec:
  ports:
    - name: "11213"
      port: 11213
      targetPort: 11211
  selector:
    io.kompose.service: url-shorten-memcached
status:
  loadBalancer: {}
