apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: user-service
  name: user-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../DeathStarBench/socialNetwork/docker-compose.yml --volumes hostPath
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/socialnetwork-default: "true"
        io.kompose.service: user-service
    spec:
      containers:
        - command:
            - UserService
          image: deathstarbench/social-network-microservices:latest
          name: user-service
          ports:
            - containerPort: 9090
              hostPort: 10005
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /social-network-microservices/config
              name: user-service-hostpath0
      hostname: user-service
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/vm_test/DeathStarBench/socialNetwork/config
          name: user-service-hostpath0
status: {}
