apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: user-timeline-mongodb
  name: user-timeline-mongodb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-timeline-mongodb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/socialnetwork-default: "true"
        io.kompose.service: user-timeline-mongodb
    spec:
      containers:
        - image: mongo:4.4.6
          name: user-timeline-mongodb
          resources: {}
      hostname: user-timeline-mongodb
      restartPolicy: Always
status: {}
