apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: user-mention-service
  name: user-mention-service
  namespace: default
spec:
  ports:
    - name: "10009"
      port: 10009
      targetPort: 9090
  selector:
    io.kompose.service: user-mention-service
status:
  loadBalancer: {}
