apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file ../DeathStarBench/socialNetwork/docker-compose.yml convert --volumes hostPath
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: user-timeline-service
  name: user-timeline-service
  namespace: default
spec:
  ports:
    - name: "10003"
      port: 10003
      targetPort: 9090
  selector:
    io.kompose.service: user-timeline-service
status:
  loadBalancer: {}
